### ISSUE TITLE
DMXSerial has conflict with SD library

### ISSUE THREAD

**Issue by dstueven** [mathertel/DMXSerial#14]
I am trying to use the SD library (to read a file from an SD card) and DMXSerial together.
Unfortunately both seem to define the same interrupt - the compiler throws an error - even if I compile a totally empty project with just the two include statements.

My minimized test sketch:
<code>
#include <SD.h>
#include <DMXSerial.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
</code>

The error messages of the compiler:
Arduino: 1.8.5 (Windows 10), Board: "Arduino Ethernet"

HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':

(.text+0x0): multiple definition of `__vector_18'

libraries\DMXSerial-master\DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here

HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':

(.text+0x0): multiple definition of `__vector_19'

libraries\DMXSerial-master\DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Ethernet.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by mathertel** [comment]
This is a know issue of the SD library: It uses the Serial interface for debugging output purpose.
> HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':

I propose you to remove all the Serial references in your local SD library.
