### ISSUE TITLE
SoftwareSerial and DMXSerial

### ISSUE THREAD

**Issue by cstranex** [mathertel/DMXSerial#17]
Is it possible to use other serial devices using SoftwareSerial while DMXSerial is running in receive mode?

**Comment by Yona-Appletree** [comment]
I'm running into issues with that as well. Probably something to do with the interrupts? I'd love to know if this is possible.

**Comment by arneboe** [comment]
Am running into problems as well, receiving only works on the first few channels when software serial is enabled.

**Comment by mathertel** [comment]
As I know SoftwareSerial is disabling interrupts and will interfere with the DMX that relies on receiving the interrupts from the hardware based serial port.

When requiring another serial port please use an Arduino Mega or Leonardo that supports 2 ports in Hardware.

/Matthias Hertel/

________________________________

**Comment by arneboe** [comment]
thx for the info :-)
