### ISSUE TITLE
noDataSince  issue returne value over 4000000000

### ISSUE THREAD

**Issue by Brecht1987** [mathertel/DMXSerial#19]
314// Calculate how long no data packet was received 
315 unsigned long DMXSerialClass::noDataSince() 
316 { 
317   unsigned long now = millis(); 
318   return(now - _dmxLastPacket); 
319 } // noDataSince() 

you can fix it to add a if 

// Calculate how long no data packet was received 
unsigned long DMXSerialClass::noDataSince() 
{ 
   unsigned long now = millis();
   unsigned long DataSinceTime =now - _dmxLastPacket;
   if(DataSinceTime <4000000000){
     DataSinceTime = 1; 
   }
   return(DataSinceTime); 
 } // noDataSince()

**Comment by mathertel** [comment]
current implementation handles the unsigned long overflow correctly.
The proposal is not required and mapping all times to `1` is unwanted.
Good docu on the problem:
http://www.leonardomiliani.com/en/2012/come-gestire-loverflow-di-millis/
