### ISSUE TITLE
Receiver responds to multiple DMX addresses unintentionally

### ISSUE THREAD

**Issue by stumouse** [mathertel/DMXSerial#21]
I've used the library for a simple DMX receiver based on the DMXShield with no isolation.
I'm wanting the device to be set to receive a single dmx channel and implement a function when the value of that channel goes above 128. 
However my project responds to multiple addresses and not just the address of 001 as stated in code.

Setup as dmx receiver with the following snippets:
`DMXVALUE = DMXSerial.read(1);`

` if (DMXVALUE >= 128){`
//do thing

Anything obvious in the code i'm missing or is this a hardware issue (apologies if so)

**Comment by mathertel** [comment]
This is likely some timing or hardware related problem.
closed - not enough information to reproduce the problem.
