### ISSUE TITLE
Serial error with UNO

### ISSUE THREAD

**Issue by gurvansz** [mathertel/DMXSerial#28]
Dear,
I try to use your library with an arduino UNO but when i want to compile the example code i have some errors.

`HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_18'
/var/folders/j2/rq93bv2x6lbg14z3qkwqfv580000gn/T/arduino_build_836542/libraries/DMXSerial-master/DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_19'
/var/folders/j2/rq93bv2x6lbg14z3qkwqfv580000gn/T/arduino_build_836542/libraries/DMXSerial-master/DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status`

Please, could you help me?

**Comment by mathertel** [comment]
As there is only one serial interface on UNO boards it is not possible to use it for 2 purposes.
There are options. See #7
