### ISSUE TITLE
2 Universes on a board 

### ISSUE THREAD

**Issue by JLightMedia** [mathertel/DMXSerial#29]
Does this library support to generate 2 DMX  universes at the same time?

**Comment by imayoda** [comment]
yes, just use a dev board that exposes the tx1 pin..
you will also loose the possibility to have serial debug on

**Comment by JLightMedia** [comment]
Hello! Thanks for answer. But how defined two different pins for out put and how to  describe two different universes  in a program code?

**Comment by imayoda** [comment]
sorry pal, been confusing as i was reading the esp8266 thread but responded here thinking it was an esp8266 question.. my mistake, really sorry

**Comment by mathertel** [comment]
No. Just one DMX universe.
There is only one Serial interface implemented and there is only one set of service routines for this interface. The interface can be selected by using pre-precessor directives.
