### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by Kirdone** [mathertel/DMXSerial#47]
Hi ! 
I have a little compilation problem. I don't know where my problem may come from.

Program :

![image](https://user-images.githubusercontent.com/69429295/89736651-34c67a80-da6b-11ea-9a57-ca4acb120dca.png)

Do you have an idea ?

**Comment by oeerenn** [comment]
I'm not sure but it's because of the serial phrases. If you delete the Serial.begin it will probably compile. But i dont know why really.

**Comment by mathertel** [comment]
you can use the Serial interface only once.
You use it as debug stream with text and the DMX protocol.
Both libraries (Serial, DMXSerial) work with interrupts (25 and 26) but only one can use it.

**Comment by mathertel** [comment]
See also #7
