### ISSUE TITLE
RC oscillator 8Mhz support

### ISSUE THREAD

**Issue by imayoda** [mathertel/DMXSerial#5]
Just asking, as per title, (with good manual freq. calibration) would it be possible to support no crystall operation in reduced frequency? 
Maybe there's still enough time to receive some dmx channels considering irq based apporach used in your lib.
BTW kudos

**Comment by mathertel** [comment]
The time for the IRQ routine is indeed one problem you have to check but you also need time in your program as well.
250.000 baud with 8 MHz can be done. See http://wormfood.net/avrbaudcalc.php for details.
I propose that you gibe it a try.

**Comment by imayoda** [comment]
Will try and post back if I get results, thanks a lot.

**Comment by imayoda** [comment]
I'm back, excellent results with 8MHz internal osc.. 2 of 3 atmegas are working properly and stable with quite heavy receiving code and at least 4 analogWrite pwms active and looping fast. On the third chip a little OSCCAL fine setup fixed the problems (signal loss and blinkiness).
Very nice job you did with self defining serial setup.

**Comment by mathertel** [comment]
Thanks @imayoda for this information and your testing. 
So it works on 8MHz ATMega boards without any modification to the software and you don't need the crystal and 2 caps. 
I hope the 8MHz is stable enough even when it gets warm or cold and adjusting the OSCCAL needs some equipment.
If you have any long time experience on this it would be great if you can comment that here.

**Comment by imayoda** [comment]
Almost one year later followup, I report excellent performances @8MHz with bare rc osc..
Used absolutely original 328 and 328pu for 2 distinct dmx receiver projects, and they worked good in harsh env temperatures (10°C-40°C)..
Well done :)

**Comment by mathertel** [comment]
Thanks ! :-)
