### ISSUE TITLE
DMXSerial conflicts with i2c WIRE library?

### ISSUE THREAD

**Issue by Suicufnoc** [mathertel/DMXSerial#6]
Hey, I'm trying to get your DMX Serial library working alongside an i2c LCD library, but as soon as I #include DMXSerial.h, the LCD screen stops working. Any ideas? should the library interact with the wire library or analog in pins 4,5? thanks

**Comment by mathertel** [comment]
Hi,

please let me know what library you use. There are many ways of how they can conflict.

Regards,
Matthias

Von: Suicufnoc
Gesendet: Montag, 5. September, 00:39
Betreff: [mathertel/DMXSerial] DMXSerial conflicts with i2c WIRE library? (#6)
An: mathertel/DMXSerial

Hey, I'm trying to get your DMX Serial library working alongside an i2c LCD library, but as soon as I #include DMXSerial.h, the LCD screen stops working. Any ideas? should the library interact with the wire library or analog in pins 4,5? thanks

-
