### ISSUE TITLE
DMX Sniff example not compiling

### ISSUE THREAD

**Issue by stijnb1234** [mathertel/DMXSerial#64]
I get the following error:

```
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_18'
libraries\DMXSerial\DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_19'
libraries\DMXSerial\DMXSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```

I'm compiling for an Arduino Uno.

**Comment by stijnb1234** [comment]
I'm stupid, it's mentioned in the comments above....

**Comment by mhlsf** [comment]
I'm having the same issue, may I know the solution ? @stijnb1234

**Comment by stijnb1234** [comment]
> I'm having the same issue, may I know the solution ? @stijnb1234

"This only works on boards with multiple UARTs (like the Mega2560), or with a virtual USB serial port in addition to a normal UART (like the Leonardo or Micro)."

The Arduino Uno only has one UART available.
