### ISSUE TITLE
Possible to use USB Serial communication?

### ISSUE THREAD

**Issue by ElectricCookie** [mathertel/DMXSerial#7]
Hi, I'm currently gathering the parts needed for the DMX shield you've put together on your website and I was wondering if it is still possible to use the Serial-Interface along with this library. I need to send commands from the PC to the Arduino.

Thanks in advance!

**Comment by mathertel** [comment]
Hi,

it depends on the hardware you use.
I wrote about the options some years ago:
http://mathertel.blogspot.de/2013/05/update-for-dmxserial-library.html

Best Regards, Matthias
