### ISSUE TITLE
Compatibility for Wemos D1 (ESP 8266)

### ISSUE THREAD

**Issue by einlichtvogel** [mathertel/DMXSerial#75]
Is the libary compatible with the above given Microcontroller?

**Comment by mathertel** [comment]
Was:
The library is not agnostic to any CPU architecture.
I use it on Arduino UNO, ESP8266, ESP32.

**The above statement is NOT TRUE**

sorry, this comment accidently was given to the wrong library.

**TRUE**: The DMXSerial library only supports the CPUs mentioned in the [README.md](https://github.com/mathertel/DMXSerial/blob/master/README.md) file.

**Comment by einlichtvogel** [comment]
Okay, but for any reason, it won't build for non avr-arch.
Maybe I just haven't updated?

**Comment by mathertel** [comment]
The DMXSerial library only supports the CPUs mentioned in the [README.md](https://github.com/mathertel/DMXSerial/blob/master/README.md) file.
See above correction.
